services:
  - type: web
    name: aayush-blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn writings.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: yourprojectname.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
