# Generated by Django 5.1.7 on 2025-07-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
    ]
